---
title: "Gridiron Genius"
author: "Michael Lombardi"
format: html
---

### Bill Walsh

- Champions behave like champions before they’re champions

- Obsessed with perfection - pushed everyone in orgnaization to LEARN more

- Counter groupthink in the NFL by building a better culture 

- Seek intelligence, not necessarily experience 

- Too much experience means you might not be able to clear your head of old ideas to make room for new ideas 

- Dee Hock said the problem is never how to get new, innovative thoughts into your mind; but how to get old ones out 

### Standard of Performance 

- Walsh's version based off the Standard of Excellence book (In Search of Excellence by Peters and Waterman)

- Promote internal communication that is open *and* substantive 

- Be deeply commited to learning and teaching, be fair

- Honor the direct connection between details and improvement, relentlessly seek improvement 

### Culture 

- Peter Drucker said culture can eat strategy for lunch

- Manage the culture, wins would take care of themselves

- Can't cookup success unless you have the right culture

### Scouting/Players Development 

- See players not as a collection of data and stats, but in **context** of schemes they run 

- It's lazy to grade a player without understaning the player's role 

- Scout inside out, not outside in - analysis is informed by detailed understanding of each position defined by the scheme

### Qualities of a Leader 

- Command - the room, the message, and one's self 

- Sophocles said all men make mistakes, but a good man yields when he knows his course is wrong and repairs the evil. The only crime is pride 

- Ultimate sign of strength is personal accountability

- Share credit and blame alike 

### Command of opportunity and process

- Bob Seger told Glenn Frey - to make it in this business, he would have to write his own songs. Frey asked, but what if they're bad? 

- Seger told him - of course, they're bad. Just keep writing until they're good 

- Same is true as a coach, you learn on the fly 

- When rules don't apply to everyone, it causes chaos

### Al Davis: Scouting 

- Our job is to find talent, not dismiss it - be professional 

- Background of a draft pick is valuable - Al Davis loved good high school players because what if their collegiate production was squandered by poor coaching or a mismatch in talent/scheme 

- Focus on the level of competition - huge variation of talent in college—from program to program and conference to conference—and how not being able to compare apples to apples impacts draft evaluations 

- Davis was drawn to players who were at their best against the best 

### Evaluating talent 

- Confirmation bias: eager to see what we want

- Remember to never begin with the end in mind

- Don't get caught up in groupthink 

- You can't bullshit an NFL lockeroom - players know who is good and bad, who the favorites are

- Best teams force players to prove their value 

### Character assessment 

- Assessing character is a challenge: too many vairables 

- Sliding scale of what is right and wrong

- Character can only be assessed face-to-face

### Belichik's secrets 

- Performs an autopsy after every season - clean slate for all, no one is grandfathered in 

- How to tweak how we teach - take the lesson from the meeting room to the classroom to the field 

- Connect emotionally on the field, but also be objective in GM decisions 

- Everyone can have an opinion as long as there is data, insight, or experience to support it 

### Team building 

- Every team has a list, but Belichik's is a living/changeable document 

- Needs change as injuries happen and skill increases, can't ignore that 

- Contentment is the enemy 

### All-in mentality 

- Special teams are the heart and soul of a team 

- Herb Brooks, USA Hockey - gave all the players a test, goalie Jim Craig refused to take the test

- Before Olympics, Brooks told Craig he might bench him and Craig though it was because he wouldn't take the test

- Brooks said - no, it's because I want the guy back that wouldn't take the test - the fire/motivation 

### Quarterback play 

- Walsh belives the feet were more important than the arm 

- Quick feet, quick arm. Balanced feet, balanced arm. Coordinated feet, coordinated attack.

- Timing was everything - spacing and rhythm, it was synchronized 

- Offense was about preserving the lead than establishing it 

- Winning (and losing) are habits - Parcells' golden rule was a QB that had at 23 wins in college 

- Yards per attempt - shows what a quarterback is seeing and where he's looking

- Thick skin - how do you react when something doesn't go your way? 

- Football smarts - study and work, but also how fast can you process information 

### Defensive Principles 

- Belichik is not much for change, but believes in adaptation 

- Disguise is as important as defense - base that tweaks play to play based on strengths/weaknesses 

- New plays don't win consistently, but using old plays in new ways does 

- Learn how an offense works: how, when, where, and why every player on the field moved during every play 

- Details over everything - inches in an offensive lineman's split stance are important 

- Teach defense, don't just coach it 

- Make the offense play left-handed - take offense out of their comfort zones by preventing them from doing what they do best 

### Remember Newton's Second Law 

- Belichik likes speed: wants his team doing, not wondering what to do, reacting, not thinking

- Hates mistakes, but if they happen it's because his team is going fast and doing, not slow and confused 

- Pressue first, sacks second - be strategic, save certain pressure for the second half 

### Four-point plays

- 3rd downs in the red zone are four-point plays - difference between a touchdown and field goal 

- Force teams to take small, harmless gains - this bring impatience and gets them to make a mistake 

### Middle Eight

- Final four minutes of first half and first four minutes of second half 

- Keep offense off the field by controlling the back at end of first half and getting the ball to start the second 

- This means you get more possessions or chances to win 

### Talking is Winning

- Talking is winning, especially on defense 

- Belichik removed numbers on players jerseys in practice because he wanted them to talk more during plays 

### Playoff gameplanning

- Experience is not preparation.

- Having previously played in a playoff game means nothing.

- Belichick's guide (1) what his team does well (2) what it doesn’t do well (3) what he thinks it will take to win the playoffs in a particular year 

### Hidden yards 

- Yards that don't show up in stat sheet 

- Example: a gunner on the punt team fighting through three blocks to down the ball at the 1 instead of letting it bounce into the end zone for a touchback. It won’t show up on the stat sheet, but that guy just saved the Ravens 19 yards in a game that will be determined by inches. 

### Opportunity period 

- Giving practice reps to backups because it might happen 

- Colts didn't believe that - Peyton Manning took all the reps - we don’t practice fucked, bad idea 

- Allow players to be ready 

### Thinking ahead 

- You're playing against the clock too: each play takes six seconds, 54 seconds = 9 plays 

- Maximize the number of yards you can get, don't check down 

- World class pool players make a shot and where they leave the cue ball matters almost as much as pocketing the ball

- Missed field goals are turnovers because after a miss, you lose possession and yards

### Noticing coverages and matchups 

- All a QB cares about is the middle of the field open or closed? 

- Check where safeties are - open or back, means middle of field is vulnerable - closed or forward, means ball likely going to sidelines 

- If a wideout is in motion and someone follows him, it's man-to-man coverage - if not, it's zone coverage 

### Born to run theory 

- Key to success is repetition, 10,000 hours of practice 

- But that gets boring - don't get bored, Springsteen plays Born to Run a lot

- Best remedy for boredom is reading and research 

### Quotes 

- To live in the past is to die in the present.

- J. Roscoe Miller said: I have two kinds of problems: the urgent and the important. The urgent are not important and the important are never urgent.

- Walsh on three F’s of decision making: firmness, fairness, fast.
  