---
title: "The Art of Nonviolent Communication"
author: "Micah Salaberrios"
format: html
---

### Fundamentals

- Communication becomes harder when we accuse, criticize, and judge

- Judgement is an opinion: not right or wrong

### What to use instead

- Facts, feelings, needs, and requests

- Leave evaluations, judgements, criticism, analysis, advice, accusations, and opinions behind

- Can you please stop tapping your foot? It's really annoying (bad)

- You're tapping your foot and I'm feeling annoyed because I would like silence to focus right now. Would you be willing to stop or go in the other room? (good)

### FFWR

- Fact, Feeling, Why, Request

- recipe for better communication

### Facts vs Evaluations

- Your room is a mess (evaluation)

- Your bed is unmade, there are dirty clothes on the floor and you have a pile of trash in the corner (observable facts)

- Your driving recklessly (evaluation)

- You're driving 20 miles over the speed limit and you just ran a red light (facts)

### Feelings and Accountability

- No matter what happens, you are responsible for how you feel 100% of the time

- I feel annoyed (accountable) vs you're annoying me (blaming)

### Common missteps

- Using "I feel . . ." is usually an evaluation disguised as a feeling

- Stay away from verbs that imply blame: tricked, ambushed, bullied, provoked, insulted, criticized, ignored

### Unmet needs

- Easy step to leave out, but important to include the need

- Usually starts with because

- When you showed up late to our meeting, I felt angry because I don't like people to waste my time (guilt trip)

- When you showed up late to our meting, I felt angry because my time is very important to me (good)

### Requests

- A request is something that can be refused without punishment

- It is also measurable and doable

### Specific Requests

- Avoid vague, unmeasureable requests

- Would you be willing to be careful with your spending? (vague)

- Would you be willing to write down everything you spend money on for the next two weeks? (specific)

### Requests vs Demands

- It's about needs being met, not the specific request

- The requests are possible strategies to getting our needs met

### Never compromise

- The goal is to get both parties needs met completely

- Keep communicating until you find a win win

### Emergency Empathy

- Use this in the moment when things get out of hand

- Guess how someone feels and why they feel as they do

- Are you feeling angry because they're leaving out important details?

- People love being asked about themsevles and feeling like someone is try to understand where they are coming from

### More principles

- We are all responsible for how we feel

- Feelings are generally one word

- Mistakes lead to wisdom
