---
title: "Mental Models"
author: "Kevin Wagonfoot (Charlie Munger)"
format: html
---

### Fast + Slow Thinking

- When information is scarce, you jump to conclusions

- Slow thinking is critical and problem solving

### Loss + Risk Aversion

- People tend to prefer avoiding loss instead of acquiring similar gains

- Risk means you're operating with incomplete information

### Confirmation Bias

- Human tendency to look for facts and evidence to support your existing beliefs

- People put a lot less effort into picking apart evidence that confirms what they already believe

### Paradox of Choice

- Having too many choices can be a bad thing

- Making choices take time and mental energy, often it is better to limit options

### Hanlon's Razor

- Always try to stay above an instant emotional response, especially before you know the other
person's true intentions 

- Never attribute to malice that which is adequately explained by stupidity

### Ad Hominem

- Practice of insulting an opponent personally instead of arguing their position

- I always cheer up immensely if an attack is particularly wounding because I think, well, if they attack one personally, it means they have not a single political argument left.

### Entropy

- Without investing energy things will tend to become more disordered over time

- You can't unscramble egg 

### Theory of Influence

- Six principles 

- Reciprocity, scaricity, authority, consistency, liking, and social proof

### Occam’s Razor

- The simplest solution is probably the correct one 

- The explanation requiring the fewest assumptions is most likely to be correct

### Murphy’s and Hofstadter's Law

- Murphy's Law: anything that can go wrong will go wrong 

- Hofstadter's Law: It always takes longer than you expect, even when you take into account this law

### Counterfactual Thinking

- Every time you say to yourself “if only i had done…” or “what if…” you are engaging in thinking that is
counter to the facts

- Because the arrow of time only points in one direction it is impossible to realize these different choices

### Parkinson's Law

- Without careful planning tasks will expand in scope and complexity until they are too difficult to accomplish

- Work expands so as to fill the time available for its completion. 

### Lateral Thinking

- Look for new ways to approach a problem to find novel solutions

- Do not seek to follow in the footsteps of the men of old; seek what they sought

### Inversion

- Instead of setting goals from what you want, try to do the opposite and set anti-goals for what you are trying to avoid 

- A lot of success in life and business comes from knowing what you want to avoid 
 

### Addition Through Subtraction

- Being creative is involved in repackaging or reimagining a great idea, simplifying it or applying it to a different purpose

- The soul grows by subtraction, not addition 

### Anecdotal Reasoning

- Anecdotal evidence is the story someone tells that provides information or a conclusion 

- The problem with anecdotal evidence is that it takes a single point of view into account 

### Correlation vs. Causation

- Correlation is a mutual relationship between two or more things 

- Causation is a relationship of dependence between two or more things 

- Correlation does not equal causation

### Tactics vs. Strategy

- Strategy describes the goal and how to reach it 

- Tactics are the specific actions to take on the way to the goal 

### Third Story

- Putting yourself in the shoes of a neutral, third-party, such as a mediator and telling a story that all parties
can agree upon

- When you voice your disagreement, begin by talking about what you have in common with the person you are arguing with

### Zero Sum Game Theory

- When one player wins, his opponent loses an equal amount 

- In a zero-sum game, the problem is entirely one of distribution, not at all one of production 

### Framing, Anchoring, and Ordering 

- Framing is the way in which something is defined 

- Anchoring deals with setting a reference point for comparison

- Ordering describes how the order that different choices are listed informs a customer's perception of value 

### Nash Equilibrium

- Assuming that all the players know the rational move that every other player will make, and they will also make a rational move, the game will reach a state of equilibrium 

### Dunning-Kruger Effect

- Those who have low ability do not have the understanding to see they are lacking ability 

- Conversely, those who performed the best underestimate their ability, assuming that everyone is able to perform at a similar level 

- Those who know do not speak, those who speak do not know

### Spacing Effect

- Spacing out repetitions over time produces better recall than doing the same number of repetitions over a shorter duration 

- Studying is like rowing a boat upstream, not moving forward is to fall behind 

### Deliberate Practice

- Method to acheive top performance in a given field

- 10,000 hours rule 

### Gamifaction

- Adding a level of competition to something that is already being done in order to improve the outcome 

### Opportunity Cost

- Opportunity cost is the tradeoff you make when you make a choice 

- the idea that once you spend your money on something, you can't spend it again on something else

### Pygmalion Effect

- Higher expectations lead to better performance

- Leaders should make sure people can emerge and grow

### Peter Principle

- Satirical concept that individuals within a large organization will continue to be promoted until they reach a job level they are unable to effectively perform 

### Circle of Competence

- Focus on areas of knowledge and ignore areas you don't understand 

- The important thing is not how big the circle is, the important thing is staying inside the circle
