---
title: "The Numbers Game"
author: "Chris Andersen and David Sally)"
format: html
---

### Insights

- Information is all over the place, almost too much data 

- The power isn’t in the data, but the insights you pull out it  

- Much tougher than it seems.

### Truth > Beliefs

- Bill James quote: what is true is more powerful than what you believe 

- Good quote to explain why you should be data driven or evidence driven 

### Dogs that don't bark 

- Tackles are a poor way to evaluate defenders

- It’s about being in the right position, so you don’t have to make a tackle

- Best defenders are dogs that don’t bark 

### What doesn't happen 

- Pay attention to what doesn’t happen 

- It’s more important to not concede a goal than it is to score a goal 

### Avoid turnovers

- Avoiding turnovers is important to success 

- Passing percentages are useful, but avoiding turnovers is more important 

### David vs Goliath 

- Gladwell on David vs Goliath: underdogs need to acknowledge their weakness, and adapt or they’ll die 

- Goliath doesn’t need to try something unconventional. Underdogs like David do.

### Failure

- Failure is often only accepted if you do it in a recognizable way 

- If it's unconventional, more criticism for failure 

- It's safe to fail in a conventional manner 

### Weakest link 

- Success in soccer is more about the weakest link, avoiding what you do badly 

- In basketball, one player makes up 20% of players on the court for you team 

- In soccer, it’s just 9% - there are superstars, but better to pay attention to a team’s weakest link 

### O-Ring Theory

- One small manufacturing part can be a multi-million dollar disaster 

- Pay attention to the details, and to your weakest link 

### Köhler effect 

- When a person works harder as a member of a group than when working alone 

- Example from a seamstress lab where they stop paying by individual and start paying by group, and it helps produce more fabric/clothes 

- Same is true in sports 

### Problems 

- Is it a tough problem, or the same problem every year? 

- Measure of success is that you’re making progress, not the same problem over and over 

### New Tactics 

- Organizational: only two paths, either your more innovative or spend more money 

- The game is decided in the margins, where light and dark meet

### Future of Tactics

- A team of 150 people (organization) is the future of tactics 

- Example is how teams are tracking players in space, their every movements, especially when they don’t have the ball 

### Practice 

- The apprenticed is a quite distinct person from the anointed 

- A violinist asked how many hours I should practice, and his mentor said, ‘It doesn’t really matter how long. If you practice with your fingers, no amount is enough. If you practice with your head, two hours is plenty.’

### Quotes 

- We play leftist soccer, everyone does everything - Pep

- There are two routes to success in soccer, we have found. One is being good. The other is being lucky. You need both to win a championship

- The great tragedy of science, the slaying of a beautiful hypothesis by an ugly fact 

- The ball is round, so that the game can change direction

- Success is determined not just by what you do well but what you don’t do badly.

- The idea that sacking managers is a panacea for a team’s ills is a placebo. It is an expensive illusion

- 2 strategies for better soccer: either being more efficient or being more innovative than your opponents 

- Both efficiency and innovation should bring more attention to the darker, defensive side of the pitch 
