---
title: "Scorecasting"
author: "Tobias J. Moskowitz and L. Jon Wertheim"
format: html
---

### Whistle Swallowing

- All about officials and omission bias with loss aversion 

- Uses Mike Carey and David Tyree catch as fundamental example.

### Acts of Omission 

- The absence of an act - as far less harmful than acts of commission - actually committing the act, even if the outcomes are the same or worse 

- Food example - declining healthy food is a poor choice (omission), but eating junk food is worse (commission) 

### Omission or Comission 

- Jeff Bezos quote - “people overfocus on errors of commission, failure’s not that expensive, the big cost you incur is harder to notice, errors of omission.”

- Officials or refs, when the game steps up, you step down

### Subjective calls

- Swallow the whistle with judgement calls versus subjective calls when the game is about to end 

- Subjective in football - holding, illegal blocks, illegal contact, and unnecessary roughness don’t happen as often when game is on the line or at its end 

- Objective calls - delay of game, illegal formation, motion, or shift are called at the same rate 

### Go for it 

- Kevin Kelley always going for it on 4th down and never punting 

- He plays the odds and he also has job security and freedom to do so

- All about risk aversion 

### Losing hurts 

- Sparky Anderson - losing hurts twice as bad as winning feels good.

- Would you rather want a $5 discount or avoid a $5 surcharge?

### Why take risks

- You’re more likely to risk something when you expect to lose 

- Job security is huge. Are you allowed to fail or be unconventional?

- Belichick was not as aggressive until he won a Super Bowl. It built equity for him to take risks, fail, and not lose his job 

### LaRussa example 

- Players must buy in too.

- Tony LaRussa tried using pitchers for 3 innings apiece, but players didn’t like it. They wanted wins (throw for 5 innings), because it drives their contracts 

### Westhead example

- Paul Westhead's playing style at Lakers, didn’t work 

- It worked at Loyola Marymount, but failed spectacularly with Denver Nuggets 

- Players buy in matters.

### Tiger Woods is human

- More about loss aversion, it’s a principle we dislike losing a dollar more than we enjoy earning a dollar 

- PGA tour, measured putts from identical distance for birdies and pars, putts for par were far more successful 

- Players were so concerned with a loss, you’re more aggressive in avoiding bogey than scoring birdie 

### Birdie putts

- Tendency to leave putts short for birdie, being too conservative.

- Woods even says the psychological difference between making a birdie and dropping a shot is huge, more important to make a par putt. He’s human 

### Gain and loss

- In the face of gain, we’re conservative

- In the face of loss, we’re aggressive.

- It’s hard to block out how you got in a predicament. Remain even keel 

### Endowment effect

- Feel the loss of something you own much more deeply than the loss of something you don’t own 

- When you own, you're invested emotionally in a thing versus not tied to it 

### Offense wins Championships

- Defense is no more important than offense, both are equally important

- Defense requires effort, it’s less glorified, harder to measure, and dark (hidden) 

### Value of a blocked shot 

- The value of blocked shots is in the details.

- Blocked shot back to opponent was assigned a value 

- Blocked shot out of bounds was slightly more valuable 

- Blocked ball to a teammate was worth the most 

### Value of the act

- It’s the value of the act, not the act itself that matters

- Counting is easy, measuring value is hard

- Tim Duncan’s 149 blocks were more valuable than Dwight Howard’s 232 blocks

### Rounding first

- People have a bias to round numbers 

- It’s why more batters hit .300 than .299.

- A batter is close to .300 at end of season? He won’t play.

### Incentive bias

- A rounder number (100 RBI, .300) usually leads to better salary 

- Bobby Abreu finished with exactly 20 or 30 home runs five times, seven times exactly 100 or 100 RBI, and no seasons with 95 to 99 RBI

- Same true in NFL with 1,000 rushers 

### Where to find value? 

- You can find value in looking at players just below these round number benchmarks

- Just below .300 or below 1,000 rushers 

### Rooney Rule 

- The drop-off of African American coaches winning is actually a good thing

- Why? It validates the Rooney rule 

- Black coaches are held to same standard as white counterparts. They’re equal 

### Comforts of Home 

- There is a home-field advantage in all sports 

- It’s a bit more strong in some sports, but it’s the same regardless of where sport is played 

- There is significant incentive to win at home - concessions, people leave happy, spend more money 

### Why does home field advantage exist?

- Because of crowd support? No. Look at kicks in football, free throws, shootouts - when you control for a situation where crowd could impact game, it really doesn’t 

- Because of travel? No, evidence isn’t strong that travel plays a major role.

- Because of scheduling? Yes.

### Scheduling

- NBA teams play lots of back-to-back games, and this does favor the home team 

- It’s less of an issue in certain sports like MLB 

- More extreme in college football. Teams pad schedule with hosting weak opponents 

### Home field advantages

- Scheduling bias explains some of home field advantage, but not in baseball or NFL or soccer at all

- Because of unique home characteristics? Not really, some impact, but not huge difference. Hard to really have an edge with unique home fields today 

### Officials

- Officials or referee bias is most significant factor

- Study used QuesTec data to determine officials or umpires side with the home team in pressure situations on borderline calls 

- More ambiguous the call? More likely to go in home team’s favor.

- Humans conform because they want to fit in and because they believe the group is better informed than they are

- Officials aren’t really aware of the bias, it’s just a natural human response

- Why does home field advantage differ across sports?

- Because refs or officials are more important or have more influence on the game. Soccer more than baseball. A penalty kick is huge, where umpire calls are fairly black and white.

- Why is it the same for a sport no matter where its played?

- Because the role of the referee is the same no matter if soccer is played in America or Europe or Spain.

- Why hasn’t it changed much over time?

- Because the officials role hasn’t changed with the rules.

### No I in team 

- But there is an m and an e 

- There is a bigger influence of superstars in certain sports like basketball 

- Disagree with soccer, think it’s much less

- Makes sense in basketball. Only 5 players play at a time

### Michael Jordan 

- Where in baseball, a player might only get 3 at-bats a game 

- In soccer, only a few touches by your best attacker.

- Michael Jordan - There is an I in win. So which way do you want it?

### NFL Trades

- Off the chart Mike McCoy came to own the NFL draft using a value chart that was largely designed off assumptions.

- Tried to answer - what is the value of a draft pick in a certain round?

- Value of the first pick in draft was 3000, and first pick in second round 580, and final pick was 0.4 

### Charts give value

- The chart just gave the Cowboys a framework

- It more or less stated value in multiple picks versus one high pick

- Opposite is when the Saints traded eight draft picks for Ricky Williams. Overpaid by a ton 

### Why did it become obsolete? 

- Eventually when all teams started using the chart, it became obsolete 

- Thaler and Massey found inefficiencies

- Teams would overpay to pick today versus playing the long game. Not comfortable with uncertainty 

### Evaluating Talent

- It takes talent to evaluate talent.

- Draft pick value is different for different sports. Seven rounds in NFL, just two in NBA, and 50 in MLB

- Find value by looking at the details. Ask why

- Brady didn’t play at Michigan more because of political reasons than his ability

### Rule Changes

- Coin toss trumps all: If you won the coin toss in overtime for NFL, you win 61 percent of time

- This prompted changes in the NFL overtime rule. It wasn’t really fair 

### Mitchell Report

-  What isn’t in the Mitchell Report Dominican players were more likely to take steroids because of cultural and situational needs 

- All incentive bias 

- The upside was far greater for Dominican players than American players. A lot of Dominicans were much younger, where American players were older and trying to get one last big contract 

### Does icing the kicker or shooter work? 

- No. It’s a lukewarm strategy.

- Study looked at NFL kicks and NBA free throws. Found no difference in performance 

### Myth of the hot hand

- Momentum in sports doesn’t exist. We just believe it does because we like patterns 

- We don’t like mystery.

- Randomness and luck resist explanation 

### Luck

- Try flipping a coin 100 times. There will be streaks of heads or tails 

- Those streaks don’t increase the odds the next flip will land on heads.

- We do a really poor job at understanding randomness. You aren’t due for anything. Your chances do not change because of a streak.

### Sample sizes and Randomness

- The true quality of teams can be measured in large sample sizes 

- Small samples are dominated by randomness 

### Statistics

- You can make numbers say whatever you want. It’s selective. And more than one thing can be true 

- Be objective. Neutral. Look at as much data as possible to get a more accurate picture 

- Not just short-term numbers 

### Cubs cursed? 

- No, they’re not cursed or super unlucky.

- It was deeply ingrained in the team that wins and losses didn’t matter 

- Wrigley wanted fans to enjoy the ballgame, win or lose. Lovable losers 

- Cubs could lose and attendance could go up. This wasn’t the case for almost all other teams.

- Beer prices remained flat. Cubs fans went to game for experience, not for wins.

- Curses aren’t to blame or Steve Bartman.

### Purpose of the book

- Ignore data and diverse views as your own peril 

- Seek controversial or opposite opinions and challenge convention to improve your decision making 
