---
title: "Competing Against Luck"
author: "Clayton Christensen"
format: html
---

#### Progress not problems

- Customers don't have problems, they struggle to make progress

- theory helps understand the how and why instead of trial and error

### Data

- quantitative data doesn't tell you about the situation customers are in 

- nor does it tell you why they chose one product over the other
 
### Situation and circumstance

- situation and circumstance have more of an effect on whether your product or service can help a customer make progress 

- don't use a bicycle in a motor race 

- something that’s well designed for one situation can be a total failure in others

- the context of the situation matters

### Progress, not products

- A Job is defined by the progress people are trying to make in particular circumstances

- Jobs have inherent complexity

- Jobs include the functional, social, and emotional forces that cause people to make tradeoffs when making choices

- great innovation insights come through depth, not breadth 

### JTBD

- helps you understand the cause and effect of the choices customers make during their struggle

- deconstructing complex experiences into binary data destroys meaning that allows us to understand the causal mechanism

- jobs is about clustering similar stories instead of segmenting details

- there’s always more than one solution to a Job, including taking no action 

- circumstance actually changes the competitive field

- blue ocean strategy (don't compete on features, compete for different situations)

- build the right set of experiences in how customers find, purchase, and use your product

- non-consumption is often the biggest competitor

### Negative Jobs

- this is when  someone wants to make progress by not doing something 

- fruitful situation to explore 

### Job Hunting 

- enabling something new can often be more valuable than producing something new

- uncovering jobs adds narrative – language and causality 

- tells you which pieces of information are needed, how they relate, and how they can be used create value

- in order to hire a new solution, by definition customers must fire the suboptimal solution or compensating behaviour

- this includes doing nothing 

### Loss aversion

- the forces compelling change must outweigh the forces opposing change for a customer to switch

- people’s tendency to want to avoid loss is twice as powerful as the allure of gains

- it’s rare for people to be able to articulate what they want, but they can tell you about their struggles

### Big and little hires

- big hire: The moment you buy a product

- little hire: The moments you actually use the product

- failing in Little Hire moments pushes people towards a new solution

### Product versus experience

- businesses succeed because of the experiences they enable 

- not the features and functionality the business offers

- rare that the product itself is the source of long-term competitive advantage

### Inverse 

- consider who shouldn’t use your product to avoid a mismatch in expectations

- you can lose an understanding of the job when trying to add new benefits and features 

### Process 

- if you can’t describe what you are doing as a process, then you don’t know what you are doing

- processes can’t be seen on a balance sheet

- processes are much harder for competitors to reverse-engineer

### Evolve how you solve the job

- make it work

- make it good

- make it cheap 

- make it good and cheap

### Active vs passive data

- passive data is soft or in the context of the struggle (qualitative)

- active data is easy to track, feels real (quantitative)

- mistaking the model created by active data for the real world of passive data is poison for innovation

### Surface growth

- inclined to sell more products to existing customers, leading them to lose focus on the job that brought them success in the first place 

- several competitors who focus only on one job, as you expand you find you're not the best at solving any job

### Confirming data

- healthiest mindset for innovation is that nearly all data is built upon human bias and judgement

- models compared to real world 

### Job focused organization

- what get measured, gets done 

- this is only useful if what’s being measured is helping the customer make progress

- jobs provide a compass for how to shape solutions but is also a filter for what not to do

### Theory of jobs

- a job is a construct 

- an abstraction that’s rarely directly observable 

- it's intentionally precise and there are boundaries to the theory 

- not everything that motivates us is a Job to Be Done 

- well-defined jobs are expressed in verbs and nouns, not adjectives and adverbs 

- not at the right level of abstraction and you’re not uncovering a job if only products in the same class can solve the problem
