---
title: "How will you measure your life"
author: "Clayton Christensen"
format: html
---

### The Theory has an opinion 

- Data is only available about the past

- Difference in WHAT to think and HOW to think

- A good theory provides if-then statements

### Motivation

- Incentive/principal agent theory (Jensen/Meckling)

- If you want someone to do something just pay them for what you want them to do

- Too many anomalies - military very motivated, non-profits, charities, etc.

### Two-Factor Theory

- Hygiene factors - status, compensation, job security, work conditions, company policies

- Bad hygiene will equal dissatisfaction

- Good hygiene equals absence of dissatisfaction

- At best good hygiene factors make you stop hating it

- Motivators - challenging work, recognition, responsibility and personal growth

- Answer the following questions: more about building something than having something

- Is this going to give me a chance to develop?

- Will I learn new things? 

- Will I gain responsibility?

### Strategy

- 2 sources for options of strategy (Mintzberg)

- Anticipated opportunities - you can see and choose to pursue (deliberate strategy)

- Unanticipated opportunities - cocktail of problems an opportunities that emerge while trying to implement (deliberate strategy)

- Unanticipated fights anticipated for attention, capital, and hearts of management

- Stick to plan, modify, or pivot - emergent strategy

- Not discrete analytical event - it is a continuous, diverse, unruly process

- Having a focused plan only makes sense in certain circumstances

- If you’ve found an outlet that offers the requisite hygiene and motivators = deliberate

- If not in above situation = emergent/ experiment

- As you learn from each experience - adjust

### Discovery-driven planning

- What has to prove true for this to work? Assumptions embedded in numbers = fail

- Rank assumptions in order by importance and uncertainty (top = most important, least certain = bottom)

- Quickly, with little expense, test validity of most important assumptions and adjust

###  Resource Allocation

- Grove - to understand a businesses strategy look at what they actually do rather than what they say they will do

- Our resources - personal time, energy, talent and wealth

- Difference in prioritizing for immediate returns - promotion, raise/bonus RATHER than long term gains - raising children

- Strategy is created through hundreds of everyday decisions about how to spend your time, energy and money

- Nothing but good intentions, unless it’s effectively implemented

- If the decisions you make about where to invest your blood, sweat and tears are not consistent with the person you aspire to be, you’ll never become that person
 
### Good and Bad Capital

- 93 percent of successful companies had to abandon their original strategy (Bhide)

- Successful companies succeed because they have money left over after the original strategy fails, so they can pivot and try another approach (Do not spend all your money on original strategy = fail)

- Capital that seeks growth before profits is bad

- Impatient for growth and patient for profits

- Honda succeeded because it was so financially constrained it was forced to be patient for growth while it figured out its profit model

- Investments in relationships with friends and family need to be made long, long before you’ll see any sign that they are paying off

### Doing the job right

- What causes us to buy a product or service is that we actually hire products to do jobs for us

- Company must understand the jobs that arise in people’s lives, then develop products and the accompanying experiences required in purchasing and using the product to do the job perfectly, it causes customers to instinctively pull the products into their lives when the problem arises

### Understand the job of the customer

- Jobs others are trying to do is very different from the jobs that you think he/ she should want to do

- Our effort is often misplaced Work through job-to-be-done lens 

- Sacrifice deepens commitment

### Danger of Outsourcing

- Concept of capabilities - resources, processes and priorities

- Dynamic and built overtime

- Resources - most tangible, people, equipment, technology, designs, brands, information, cash, relationships with suppliers, distributors and customers

- Resources can be hired/fired, bought/sold, depreciated/built

- 1 of 3 critical factors driving business

### Processes

- Way which employees interact, coordinate, communicate and make decisions are processes

- Enable resources to solve more and more complicated problems

- Includes ways products are developed/made, and methods by which market research, budgeting, employee development, compensation and resource allocation are developed

- Can’t be seen on a balance sheet

### Priorities

- Defines how a company makes decisions, clear guidance about what a company will invest in or not

- What will employees focus on today and what will they not

- Company’s priorities must be in sync with how the company makes money

- Dynamic view of suppliers capabilities - what are they striving to do

- What capabilities must stay in house - otherwise you will hand over future of your business

### Learning 

- People learn when they are ready to learn Not when we’re ready to teach them

- Need to do more then learn new skills, need to be challenged

- Need to develop values, solve hard problems

- Hand over to others (outsource) you are losing opportunities to develop them

### Right Stuff

- Not born with superior skills, your the best because you honed them along the way

- Experiences that taught them how to deal with setbacks or extreme stress in high- stakes situations

- Abilities are developed and shaped by experiences in life

- Wrestle with the problems you don’t even know you are going to face

- Value of giving people experiences before they need them plays out in many fields other than business

- If you do not fail along the way, they will not build the resilience to get through life

- Experiences must prepare you down the line

- Find the right experiences to help build skills you need to succeed

### Culture

- Schein - a way of working together toward common goals that have been followed so frequently and so successfully that people don’t even think about trying to do things another way. If a culture has formed, people will autonomously do what they need to do to be successful.

- Casual Friday’s, free sodas in the cafeteria, or whether you can bring your dog into the office - just artifacts of culture, NOT real thing

- Result of shared learning = first time when a problem or challenge arises

- Example - How do we deal with customer complaint?

- If the decision is deemed “good enough” employees return to same decision and way of solving the problem

- Every time you solve a problem, you are learning what matters

- Creating an understanding of priorites, how to execute (processes)

- A culture is the unique combination of processes and priorities within an organization

- Advantage allows an organization to become self-managing

- If environment changes substantially, strength of the culture will make it hard to change things

- Culture is formed through repetition - must reinforce, it will form one way or another

### Full vs. Marginal Thinking

- Life comes with no warning signs Case of Blockbuster vs. Netflix

- Failure is the end path of marginal thinking

- We end up paying the full cost of our decisions, not the marginal

- Full cost of something completely new  

- Leverage what already exists

- If you need a machine and don’t buy it, then you will ultimately find that you’ve paid for it and don’t have it

- 100 percent of the time is easier than 98 percent of the time

- Instinct to use marginal costs hides us from the true cost of our actions

- Decide what you stand for and then stand for it all the time

### Purpose

- likeness - what the managers/employees hope they build when they reach each critical milestone on their journey

- commitment - conversion to likeness that they are trying to create, do not compromise

- metrics - enable everyone associated to with enterprise to calibrate their work, keep them moving together in a coherent way

- Likeness, commitment, metrics compromise a purpose

- Must deliberately be perceived and chosen, then pursued

- The Person I want to become Becoming Committed

- Find the right metric

- Resolve others challenges rather than your own, do not focus on your problems

  