---
title: "Dark Horse"
author: "Todd Rose and Ogie Ogas"
format: html
---

### Personalized success

- Living a life of fulfillment and excellence.

- Achieve personalized success by harnessing your individuality in the pursuit of fulfillment to achieve excellence

### Four elements on the Dark Horse mindset

- Know your micro-motives

- Our schools and jobs were never designed to help you figure out what whets your appetite

- These institutions believe in universal motives, but one size doesn’t fit all

### Game of judgment 

- a) Become aware when you’re judging someone/something 

- b) Identify feelings, vivid reactions, when you’re judging someone/something 

- c) Ask why you are experiencing those feelings

- The game of judgment isn’t about other people/things at all. It’s about you. It’s all about the details. The specifics.

### Motives can be contradictory

- Example: you may want to be around around people and be alone

- Don’t follow your passion

- Engineer your passion

### Know your choices

- Be the same as everyone else, only better - that’s not choosing, it’s picking

- Picking is like using a menu at a restaurant

- Choosing is going to the grocery market and cooking dinner

### Choosing vs Picking

- Choosing is an active process

- Picking is a passive process

- The true power of choice is to find and select opportunities that activate the greatest number of your own micro-motives

### Standardization mindset

- Luck isn’t a dark horse strategy

- Dark horses are ok with the worst-case scenario too

- What separates dark horses is how they evaluate risk

### Risk 

- Standardization mindset says risk is determined by odds

- Dark horse mindset says risk is determined by fit

- Because if something is a good fit, the opportunity is low risk. If a poor fit, the opportunity is a high risk 

### Susan Rogers

- She took a job as a receptionist at a studio

- The odds say an average person successfully going from receptionist at a studio to musical engineer are low. But Susan said there was a good fit between her motives, so it **wasn’t a high risk**

- A small difference in fit can lead to a large difference in fulfillment and excellence 

### Know your strategies

- Standardization says there is one best way

- The truth is there are alternatives

- Knowing your strategies is a new way of thinking about the nature of your strengths

### Micro-motives 

- Your micro-motives are part of your core identity, these are resistant to change 

- When we want something, we feel it 

- You know with confidence whether you want to go skydiving or eat a plate of eel sushi or watch the latest Marvel movie

### Strengths are the opposite 

- Inaccessible, contextual, and dynamic. Fuzzy 

- Everything you label as a strength is a artificial construct or ability

- Abilities like programming or performing ballet are done through effort or learning

### Natural talent 

- How naturally gifted are you at riding a hippopotamus?

- The only way to know is to try 

- You discern your strengths through action, not introspection 

### Contextual strengths 

- Say you have trouble reading text

- That’s a shortcoming if you want to be a literary critic

- If you want to be an astronomer, it might be an unexpected strength

- If you have trouble reading, your brain is better detecting images like black holes

### Examples of strengths/weaknesses by context 

- Empathy is an asset for a nurse, and a shortcoming for a drone pilot

- Being tall is good for an NBA player, and bad for a coal miner

### Dynamic strengths

- Improve with practice, deteriorate through neglect

- Your approach should be different when choosing a strategy than when choosing an opportunity

- It’s all about trial and error not staying the course or choosing the one best way

### Choosing a strategy 

- You should expect failure

- It’s necessary to develop excellence with strategies

- It unearths your fuzzy strengths

### Why know your micro-motives? 

- When you learn to know your micro-motives: 

- You engineer your own passion  

- Which endows you with energy and authenticity

### Why know your choices? 

- When you learn to know your choices 

- You engineer your own purpose

- Which provides you with meaning and direction

### Why know your strategies? 

- When you know your strategies 

- You engineer your own achievement 

- Which gives you a deep sense of pride and self-worth

### Ignore the destination

- Unlearn things

- Destinations are catastrophic for fulfillment

### More on standardized mindset 

- Standardized time (120 credit hours, MBA, certain degree) is to benefit institutions, not you

- Fixed dates makes it easier to assess people

- This makes you believe that getting better is simply a matter of time

### Dark horse mindset says

- Time doesn’t matter

- The correct answer is it depends because time is relative

- Don’t ask how long it takes to master something?

- Instead ask if this the right strategy for me to master something?

### Goals and destinations 

- Ignoring a destination is not the same as ignoring goals 

- A goal emerges out of your individuality 

- An active choice you have made.

### More on goals and destinations

- A destination is someone else’s idea of an objective that you acceded to. It’s always contingent 

- For example, getting into Harvard Law is a destination 

### More on goals and destinations

- A goal is winning your next debate club match, reading more philosophy books, and trying to get an internship 

- It’s possible you will end up at Harvard Law. The self-knowledge you gain from these goals will open up new opportunities for you 

### Gradient ascent

- It’s like climbing to the highest peak 

- First, you start climbing in the direction of the steepest slope 

- Next, you pause and look around to gain a new vantage point to see if that’s the right path to the peak 

- It’s not fast. You repeat this until you reach the peak 

### World believes in standardization mindset 

- Talent isn’t rare, there is a talent quota

- This makes us believe very few have the potential for excellence

- Standardization mindset selects talent

- Dark horse mindset is about developing talent

### Fairness on talent 

- A lottery system would be the only way to meet a quota and objectively evaluate candidates

- Use a jagged profile to show that everyone has talent

- Quotas lead to a negative-sum game (you win, I lose, if I win, you lose)

### Equality 

- All animals are equal, but some animals are more equal than others

- Standardization qutoacracy, you don’t need talent or hard work to climb the ladder, you need the right family or a fat wallet

- Redefine equal opportunity as equal fit

#### Best version of yourself 

- A dark horse mindset says your goal is not to become the best in the nation, but to become the best version of yourself

- Equal fit is about guaranteeing individual choice

- Ask if an institutions provide both personalization and individual choice?

### Examples 

- Choice without personalization is picking (food menu)

- Summit Public Schools example: have a dedicated mentor who meets with them one-on-one every week

- Summit uses a lottery system to accept students, everyone has an equal chance

### More examples in education 

- Southern New Hampshire University started College for America 

- It eliminated grades and credit hours, replaced with competency-based evaluations

- Every student has a mentor helping them make the best educational choice

### Southern New Hampshire University Example 

- No formal instructors, only academic coaches and reviewers

- Greater freedom of choice comes greater personal accountability

### The book in one sentence

- Get better at thing things you care about most 
