---
title: "Thinking in Bets"
author: "Annie Duke"
format: html
---

### Poker not chess

- Life is more like poker, skill and luck

- Chess is all skill.

### Resulting 

- A good decision does not mean a good outcome and a bad decision does not mean bad a outcome 

- Run a red light and be fine 

- Go on green and get in accident.

### Dr. Strangelove 

- Game theory: making decision under conditions of uncertainty overtime

- The world doesn’t easily reveal the objective truth 

- Uncertainty can work a lot of mischief.

### Process

- What makes a good decision is a good process 

- A process that accurately represents our current state of knowledge, which is always some variance of I don’t know

- More experience just means you can make a better guess 

### Reality 

- We don’t perceive the world objectively, but our goal should be to try 

- Get comfortable about not being sure and saying I don’t know 

- A loss feels twice as bad as a win feels good 

### All decisions are bets 

- Buying a house, parenting, choose steak over chicken, going to the movies

- We can only make our best guess, given what we know and what we don’t know, at what the future will look like

### Alter beliefs 

- Instead of alternating our beliefs to fit new information, we do the opposite, altering our interpretation of that information to fit our beliefs

- Our preexisting beliefs influence the way we experience the world 

- Those beliefs are formed in not an orderly way, which means mischief is in our decision making

### Opposite 

- The better you are with numbers, the better you are spinning those numbers to conform and support your beliefs 

- We bet on our beliefs, but don’t vet those beliefs well before we form them 

- We stubbornly refuse to update our beliefs. And being smart doesn’t help, it makes it *worse*

### Why be Objective? 

- Because the more objective we are, the more accurate our beliefs become

- Almost nothing is black and white, 0 or 100, and that’s pretty good philosophy for living

### How not What 

- Better served as communicators and decision-makers if we thought less about whether we are confident in our beliefs and more about **how confident** we are in those beliefs 

- This way our expression of confidence would capture all the shades of grey in-between 

- It’s a spectrum, 76% to 63% is much better than right or wrong.

### Uncertainty 

- Acknowledging uncertainty is the first step in measuring and narrowing it 

- Any decision is a bet on what will likely create the most favorable future for us.

- Sometimes things happen because of the other form of uncertainty - LUCK 

### The Problem 

- The way things turn out could be the result of our decisions, luck, or a combination of the two

- Quote: We must believe in luck, for how else can we explain the success of those we don’t like 

- Golden rule of habit change - keep the old cue, deliver the old reward, but insert a new routine 

### Strive for this 

- Be a better credit-giver than your peers

- Be more willing than others to admit mistakes

- Be more willing to explore reasons for an outcome with an open mind

- And even, and especially, if that might cast you in a bad light or shine a good light on someone else 

### What to ask 

- Why might my belief not be true?

- What other evidence might be out there bearing on my belief?

- Are there similar areas I can look toward to gauge whether similar beliefs to mine are true?

### More ?s to ask 

- What sources of information could I have missed or minimized on the way to reaching my belief?

- What are the reasons someone else could have a different belief, what’s their support, and why might they be right instead of me?

- What other perspectives are there as to why things turned out the way they did?

### Don't be a outcome junkie

- You’re going to lose a lot, and win a lot 

- You can always, however, try to make a good bet 

- Learn how to navigate the uncertain future because you’ll never be sure of the future 

### CUDOS 

- Principles for a good trust group

- Communism: be a data sharer, more data you share leads to better assessment

- Rashomon effect: two accounts of same event, but versions are dramatically different because they’re informed by different facts and perspectives

- You can’t assume your version of the story is accurate or complete

- Universalism: don’t shoot the message, imagine if same info came from person you didn’t like

- Both of these are bad: - negative opinion about person delivering message, we close our mind - positive opinion about person delivering message, we accept without vetting it

- Listen to the other side to look for things you agree with, when we do this, we learn things we otherwise wouldn’t have learned

- The only way to gain knowledge and approach truth is by examining every variety of opinion

- Disinterestedness: telling someone how a story ends encourages them to be resulters

- We don’t process information independent of the way we wish the world to be

- If the group is blind to the outcome, it produces higher fidelity evaluation of decision quality

- Organized skepticism: discussion among the group to encourage engagement and dissent

- Lean over backwards to figure out where we could be wrong

- Skepticism is about asking why things might *not be true* rather than why they *are true*

### Communication with a trust group 

- Express uncertainty: listen for things you agree with, state those and be specific, follow with and instead of but

- **and** is an offer to contribute

- **but** is a denial and repudiation of what came before

- Try using **yes and** 

### Decision making help

- Ask do you want to let it all out or are you thinking about what to do next?

- Focus on the future: we can identify the goals, our problem is the execution

### The past

- Rehashing our past can create defensiveness

- It’s hard to be defensive about something that hasn’t happened yet

- Have you thought about how you would get rid of all this drama in the future?

- Example: child with bad test scores - it must be hard to have a teacher like that, do you think there is anything you can do to improve your grade in the future?

### Consequences

- Consequences take awhile to show: what does the intern possibly know? 

- It could take years for that intern to become a successful competitor before that mistake becomes obvious

- Improving decision quality is about increasing our chances of good outcomes, not guaranteeing them

### In the moment 

- When we make in-the-moment decisions, and don’t ponder our past or future, we are more likely to be irrational and impulsive
thinking about the future is remembering the future

- Temporal discounting - favor our present self at the expense of our future self

### Regret 

- Move regret in front of our decisions: have a loss agreement 

- Regret decision of losing lots of chips before you bought more

### Think like this 

- Imagine how future-you is likely to feel about the decision or imagine how you feel today if past-you made the decision
how would you feel if you made the decision 10 minutes ago? 10 months ago? 10 years ago?

- This does two things:

- 1 - influences us to make a better decision 

- 2 - helps us treat ourselves more compassionately

### How we got there 

- It doesn’t so much matter where we end up as how we got there

- Our feelings are not a reaction to the average of how things are going

- What is tilt? If you blow some recent event out of proportion and react in a drastic way, you’re on tilt

### Long view

- Long view thinking is more rational thinking

- Ulysses contract: past-us preventing present-us from doing something stupid

- Examples: take a ride share when going to a bar, automatic allocation into retirement fund

### What is wrong? 

- Wrong is a conclusion, not a rationale

- If we’re going to be self-critical, the focus should be on the lesson and how to calibrate future decisions

### Benefits of scouting the future

- 1st: scenario planning reminds us that the future is inherently uncertain, more realistic

- 2nd: we are better prepared for how we are going to respond to different outcomes that might result from our initial decision, anticipate positive or negative developments instead of being reactive

- 3rd: being able to respond to the changing future is a good thing, being surprised by the changing future is not

- 4th: less likely to fall for hindsight or resulting bias

### Expected value: Example 

- $100,000 grant has 25% chance of winning (expected value is $100k * .25 = $25,000)
- $200,000 grant has 10% chance of winning (expected value is $20,000)
- $50,000 grant has 70% chance of winning (expected value is $35,000)

- This shows that the $50,000 grant is more valuable than the $100,000 and $200,000 grants

### Backcasting 

- When we forecast the future, the present and the immediate future look large, anything beyond that loses focus

- Prospective hindsight, imagining that an event has already occurred, increases the ability to correctly identify reasons for future outcomes by 30%

### Premortem 

- Premortem: imagine a negative outcome

- Backcasting is cheerleader, premortem is the heckler in the audience

- Incorporating negative visualization makes us more likely to achieve our goals

### Negative visualization 

- We're more likely to execute goals if we think about negative futures

- Why?

- Because it helps us anticipate potential obstacles and improve our likelihood of succeeding 

### Tree metaphor 

- The trunk of the tree is the past

- Branches are potential futures

- When a potential future doesn’t happen, don’t chop it down (give the chainsaw a rest)

### Outcomes and Hindsight

- When you look into the past and only see what happened, it seems inevitable

- Hindsight bias is the enemy of probabilistic thinking
