---
title: "The Tao Jones Averages "
author: "Bennett W. Goodspeed "
format: html
---

### How we often think

- we try to understand running water by catching it in a bucket

- remember to look for soft data, just because it’s not easily measured doesn’t mean it’s not important

- predictions are often wrong because what is not taken into account

### Taoism

- Taoism is all about how opposites are interconnected

- yin and yang, long and short, life and death are fused into one, as each depends on its counterpart for full completion

- when opposites supplement each other, everything is harmonious

- opposites get their meaning from each other and find their completion only through each other

### Wisdom

- attain knowledge by adding things, attain wisdom by removing things

- analexia: if something can’t be measured or analyzed, it’s not real

- one has to return to childlike ways by unlearning the rules of man and society, and thus be free to 

- allow the unconscious mind to work effectively

- Wu Wei means rolling with the punches, swimming with the current, and winning by attraction and attitude rather than by deed and compulsion

### How to govern or manage

- in government, one should “govern a large country as you would cook a small fish; lightly

- the more laws are enacted and taxes assessed, the greater the number of law-breakers and tax evaders

### Left Brain

- controls the right side of the body, is analytically oriented

- it reasons logically and sequentially and is responsible for our speech

- adept at math, accounting, languages, science, and writing

- like a computer, it is programmable and is nurtured by our highly analytic educational process

- the properties of the left brain are not unique; man has developed computers that can duplicate those functions

### Right Brain

- controls the movements of the left side of the body, is unique

- operates nonsequentially, is intuitive, artistic, has feelings

- gestalt-oriented (sees the forest and not just the trees)

- controls our visual perceptions

- since it’s nonverbal, it communicates to us through dreams and “gut reactions”

- provides and stores all of our nonverbal experience; a vast amount of input, certainly much more than we can verbally retrieve from our left brain

### Qualitative info

- though we are told not to compare apples and oranges, we continually do so by translating them into numbers

- in the process, we tend to lose track of their intangible properties such as taste, nutrition, and aesthetics

- we continue to honor yang values by demanding credentials of anyone who asks us to look at what is new, rather than looking at the evidence itself

### Bad Education System

- educational system emphasizes being “right” at the expense of being open

- this teaches our youth to be still, to look to authority, and to construct certainties

- it ingrains self-limiting behavior and promotes competition for the highest grades

### How to improve education system

- teaching should not be done by describing and pointing out differences, but by example

- what students need to learn is freedom, high expectations, awareness, patterns, connections, and creativity

### Teach creativity

- “Whereas the young need some sort of initiation into an uncertain world, we give them bones from the culture’s graveyards. Where they want the real thing, we give them abstract busy work, where they need to find meaning, the schools ask memorization, and discipline becomes divorced from intuition, patterns from parts.”

- we should teach creativity

### Model of creativity

- four stages: preparation, incubation, illumination, and verification

- preparation: do your homework, research it (left brain)

- incubation: sleep on it, take a walk, reflect (right brain)

- illumination: eureka moment (left and right brain come together)

- verification: confirm your discovery (left brain)

### Trends

- just before a trend changes, there will be maximum agreement by experts and others that the trend will not end

- to deal with discomfort of uncertainty, man tends to create a false sense of security by substituting certainty for uncertainty

- irony is that the greater the uncertainty, the greater the similarity of predictions, as the experts “shout” together in the dark

### Comedy and Tragedy

- a comedy is when the characters discover reality in time to do something about it; a tragedy is when the characters do not

- stupidity well packaged can sound like wisdom

###  Thinking and dealing with uncertainty

- since vision is the most information rich of all senses, visual thinking is extremely important and powerful

- in order to extrapolate what is missing, you need to use the right hemisphere, as it is by far the one best suited to deal with incomplete information

- watch out for the man whose stomach doesn’t move when he laughs

### Inference

- to infer is to arrive at a decision or opinion by reasoning from known facts or evidence (e.g., from your smile, I infer that you’re pleased)

- an inference can also be a matter of making connections between events that are not obviously related

- General Patton observed the anomaly of cart tracks and made the connection that the Germans were low on gas; a rather creative and important leap

- inferential thinking, however, is very much whole brained; the left brain stores up the knowledge acquired during the reading so as to provide a background against which the right brain can spot anomalies

### Crisis

- crisis equals danger and opportunity

- As crisis is comprised of danger and opportunity, those who sense change in the early stages will tend to have the most bountiful harvest

### Reading is important for inference

- reading serves as a “radar screen” on which the anomalies, or clues of change, first appear

- provides a feeling for what is normal, as one needs to know normality in order to recognize an anomaly

- broad-based readings allow one to spot a change in one field that will impact another
  