---
title: "How to Decide"
author: "Annie Duke"
format: html
---

### Resulting

- tendency to look at whether a result was a good or bad to figure out whether a decision was good or bad

- loose coorelation between quality of decision and quality of outcome

### Luck

- Luck intervenes between your decision and the actual outcome

- You can't tell that much about the quality of a decision from a single outcome, because of luck

- You notice bad luck but overlook dumb luck

### Range of Outcomes

- Goal is to make a decision that will lead to the most favorable range of outcomes

- Resulting reduces compassion when it comes to how we treat others and ourselves 

### Hindsight Bias 

- tendency to believe that an outcome, after it occurs, was predictable and inevitable

- Two ways: should have known and knew it all along

- Memory creep: things that reveal themselves after the fact creeps into your memory of what you knew or what was knowable before the decision

- Hindsight bias leads to lack of compassion for ourselves and others

### Decision Multiverse

- Paradox of experience 

- Experience is necessary for learning, but individual experiences often interfere with learning

- Exploring the other possible outcomes is a form of counterfactual thinking

- our willingness to example outcomes is asymmetrical 

- we are more eager to put bad outcomes in context than good outcomes 

### Preferences, Payoffs, and Probabilities

- Preference is individual to you, depends on your goals and values

- Payoff is how an outcomes affects your progress toward or away from a goal

- Some possibilities will have payoffs where you gain something of value

- These compromise the upside potential of a decision 

- Some possibilities will have payoffs where you lose something of value

- These compromise the downside potential of a decision 

- Risk is your exposure to the downside

- When you're figuring out if a decision is good or bad, you're comparing the upside to the downside

- Does the upside potential compensate for the risk of the downside potential? 

- Pros and cons lists are flat, low quality decision making tool 

- These lack information both about the size of the payoffs and the probability of any pro or con occuring 

### Six Steps to Better Decision Making 

- Identify the reasonable set of possible outcomes.

- Identify your preference using the payoff for each outcome, what degree do you like or dislike each outcome?

- Estimate the likelihood of each outcome unfolding

- Assess the relative likelihood of the outcomes you like and dislike for the option under consideration. 

- Repeat steps 1-4 for other options

- Compare the options

### Taking Dead Aim

- Likely and unlikely are ambiguous terms, it leads to miscommunication 

- Expressing probabilities as percentages is more useful and precise 

- Size of range of signals indicates what you know and what you don't know

- Shock test: would you be surprised if the correct answer was outside your range? 

### Turning Decisions Outside In

- Inside view is your view of the world 

- Many cognitive biases are in the inside view 

- Pros and cons list amplify the inside view 

- Outside view is the way others would see your situation, indepedent of your own perspective

- Accuracy leaves at the intersection of the outside view and the inside view

### Breaking Free from Analysis Paralysis

- Increasing accuracy costs time

- Saving time costs accuracy

- Key to balancing it - what is the penalty for not getting the deicison right? 

### Happiness Test

- How happy will you be in a week, a month, or a year? 

- If this was the only option I had, would I be happy with it? 

### Opportunity Cost 

- When you pick an option, you're passing on the potential gains associated with the options you don't pick 

- Higher the opportunity cost, the higher thee penalty for making choices that are less certain 

### Power of Negative Thinking

- Gap betwen the things we know we should do and the decision we later make is known as the bahavior gap

- Think positive

- Plan negative 

- Mental contrasting is thinking about how things can go wrong

- Mental time travel: picturing yourself in the future having failed, and looking back at what got you to that outcome

- This is a premortem

- Backcasting is when you work back from a positive future to figure out why you succeeded 

- Don’t confuse the destination with the route. 

- Your reaction to a bad outcome can make things worse. 

- Backcasting is when you work back from a positive future to figure out why you succeeded 

- Don’t confuse the destination with the route. 

- Your reaction to a bad outcome can make things worse. 

### Decision Hygiene

- Beliefs are contagious

- Halo effect: tendency for an impression created in one area to influence opinion in another area 
