---
title: "Are Your Lights on?"
author: "Donald C. Gause, Gerald M. Weinberg"
format: html
---

## Preface

- Problem: nobody reads prefaces
- Solution: Call the preface Chapter 1. 
- New problem created by solution: Chapter 1 is boring
- Resolution: call it Chapter 2

## What is a problem? 

- A problem is a difference between things as desired and things as perceived
- Phantom problems are real problems 

## Problem definition

- Don't take their solution method for a problem definition
- If you solve their problem too readily, they'll never believe you've solved their real problem 

## Conclusions 
- Don't leap to conclusions, but don't ignore your first impression 
- Each solution is the source of the next problem 

## Tricky part
- Trickiest part of certain problems is just recognizing they exist 
- If you can't think of at least three things that might be wrong with your understanding of the problem, you don't understand the problem 

## Misfits
- Test your problem on others 
- Each new point of view will produce a misfit 

## Problem statement
- Once you have a problem statement in words, play with the words until the statement is in everyone's head
 
## Other people's problems
- Don't solve other people's problems when they can solve them perfectly well themselves
- If it's their problem, make it their problem 

## Force the solution 
- If a person is in a position to do something about a problem, but doesn't have the problem, then do something so they do have the problem 
 
## Yourself 
- Try blaming yourself every once in awhile - even for a moment 

## No need for complicated solutions 
- Even if it's their problem, you can assist them
- If people really have their lights on, a little reminder may be more effective than your complicated solution 

## Monkey's paw
- We never have enough time to do it right, but we always have enough time to do it over
- We never have enough time to consider whether we want it, but we always have enough time to regret it

## Fish 
- The fish is always the last to see the water
- Don't rush in with a solution before the problem is defined

## Questions to ask
- What is the problem? 
- Whose problem is it? 
- Where does the problem come from? 
- Do we really want to solve the problem? 
