---
title: "Effortless"
author: "Greg McKweon"
format: html
---

### The Truth About Hard Work

- The marginal return of working harder is, in fact, negative

- When you simply can't try harder, it's time to find a different path

### The Effortless Way

- This book can't eliminate your hardships

- It won't help downplay your burdens, but it will help lighten them

- Burnout is not a badge of honor

### The Big Rocks Theory

- The large rocks must go in first to fit in the jar

- Big rocks are your essential responsibilites: health, family, relationships

- Small rocks and pebbles: work, career

- The sand is social media and doom swiping

### Right things in the wrong way

- If you don't follow the big rock theory, you'll get the trivial things done, but have no time for the important things

- Essentialism is doing the right things, effortless is about doing them in the right way

### Another way

- Acheiving our goals efficiently isn't unambitious. It's smart.

- What could happen in your life if the easy, but unimportant things became harder and the essential things became easier?

### Part I: Effortless State

- The most essential things can be the easiest ones

- If you're trying too hard, find the easier path

- Avoid burnount, and get the right results

### Part II: Effortless Action

- Perfectionism makes essential projects hard to start

- Self-doubt makes them hard to finish

- Trying to do too much too fast, makes it hard to sustain momentum

- You have to simplify the process

### Part III: Effortless Results

- Two types of results: linear and residual

- One-time benefit is a linear result

- Residual results: put in the effort once, and reap the benefits again and again

### Perpetual Load Theory

- Our brain's processing capacity is large, but limited

- Our brain is programmed to prioritize emotions with high affective value - fear, resentment, anger

- This makes the effortless state difficult

### What if this could be easy?

- Hard work may not be well named

- Trivial things are easy. Important things are hard (not true)

- We accept the right way is the harder way

### Path of Least Effort

- Cognitive ease principle: take the path of least resistance

- What if we embraced this tendency?

### When you try too hard

- Trying too hard makes it harder to get the results you want

- Behind most failures, you will find the same error of trying too hard

- In order to achieve, we must overdo (not true)

### Invert

- Turn an assumption upside down, and ask what if the opposite were true?

- What is this could be easy? Find an indirect approach

- If overwhelmed, ask how are you making this harder?

### What if we could enjoy it?

- At the intersection of essential and enjoyment is effortless

- Pair essential activities with enjoyable activities

### Release

- When you focus on what you lack, you lose what you have

- When you focus on what you have, you get what you lack

### Habit recipe

- Each time I complain, I will say something I'm thankful for

- Complaining is easy, but trivial

### Habits vs Rituals

- Habits are what you do

- Rituals are how you do it

### Rest

- Do not more today than you can recover from tomorrow

- Break down essential work in three sessions of no more than 90 minutes each

### Notice

- Awareness is about being more present

- Train you brain to focus on the important and ignore the irrelevant

- Clear clutter in your physical environment before clearing it in your brain

### How you make progress

- Pacing yourself instead of powering through

- Take the first obvious step

### Define

- Before you get started, define what done looks like

- Take 60 seconds to focus on the desired outcome

### Start

- Break the first action done in the smallest, concrete step

- 10 minute micro-burst of focused activity to boost energy and motivation

### Simply

- To make the process simpler, remove the steps

- Maximize the steps not taken

- Not everything requires going the extra mile

### Rubbish

- Zero-draft, start a project with rubbish

- Fail cheaply: make learning sized mistakes

### Pace

- Slow is smooth, smooth is fast

- Create a range: lower limit, and upper limit

- I will never do less than X, or more than Y

### Principles

- Learn principles, not just methods and facts

- Understand the first principles deeply, and then apply them

### Blue ocean

- Being good at what nobody is doing is better than being great at what everybody is doing

- Being an expert at what nobody is doing is exponentially more valuable

### Levers

- Use teaching to harness the strength of ten

- Live what you teach, and notice how much you learn

- Sesame Street it - stories that are easy to learn and understand

### Automate

- Use checklists every time, so you don't need to rely on your memory

- Seek choices that eliminate future decisions

- High-tech for essential tasks, and low tech for non-essential tasks

### Trust

- It's the engine oil of frictionless, high-functioning teams

- Make the right hire once, and it will continue to produce results again and again

- Three I's: Integrity, intelligence, initiative

### Prevent

- Don't manage the problem, solve it before it happens

- Measure twice, cut once

- It takes less time to manage the problem then solve it
