project:
  type: website

website:
  title: "Chris Gallo"
  navbar:
    right:
      - href: index.qmd
        text: home
      - href: projects.qmd
        text: projects
  page-footer: 
    left: "2023 | chris gallo | built using quarto" 
    right: 
      - icon: github
        href: https://github.com/gallochris
      - icon: mailbox 
        href: mailto:chris@hellogallo.com
format:
  html:
    theme: 
      - journal
      - custom.scss
    toc: true
