---
title: "Data Projects"
---

I analyze and visualize data to ask better questions. Data manipulation is done using the [R programming language](https://www.r-project.org/), SQL, and Ruby on Rails.   

### Active projects
-   [Bless your chart](https://blessyourchart.substack.com/): a weekly-ish data viz newsletter about college sports. 
-   [When UNC plays](https://whenuncplays.com/): a tiny Rails app to list of UNC athletic events across all sports for the 2026-27 athletic calendar year.
-   [CFB TXT](https://cfbtxt.com): a fast, plain-text site that surfaces 2026 college football data.


### Archived projects
-   [WAB Watch](https://wabwatch.com): a plain-text static site to track WAB (wins-above-bubble) over the course of the 2025-26 men's college basketball season. 
-   [BYC app](https://byc.evidence.app/): data site built with [evidence.dev](https://evidence.dev/) to complement the newsletter. 
-   [CBB Ref Logs](https://blessyourchart.shinyapps.io/cbb-ref-logs/): a Shiny dashboard that surfaces the travel schedules of men’s collegiate basketball referees during the 2023-24 season.
-   [2024 Posit Table Contest submission](https://cjg.quarto.pub/bless-your-chart/posts/byc_posit_tbl_contest/table-contest-cg.html): static HTML table that shows the 2024 ACC Baseball regular season standings submitted as part of the [2024 Posit Table Contest](https://posit.co/blog/announcing-the-2024-table-contest/).
-   [WABStick](https://blessyourchart.shinyapps.io/WABStick/): a Shiny app to compare two teams competing in the 2023-24 men’s college basketball season using wins-above-bubble (WAB). 
-   [CBB Conference Index](https://blessyourchart.shinyapps.io/cbb_conf_index/): a small app built with Shiny that surfaces college basketball standings and summarizes NET rankings with quadrant opportunities. 
-   [FBS logs](https://fbs-logs.blessyourchart.com/): a project to track the duration of college football games for the 2023 season and analyze recent rule changes. This work was mentioned in the [Washington Post](https://www.washingtonpost.com/sports/2023/08/29/college-football-made-for-tv-games/). 
-   [CFB win totals](https://blessyourchart.shinyapps.io/cfbwintotals/): another Shiny app to find the win totals of a team and its 2023 opponents. 
-   [Dadgum Box Scores](https://dadgumboxscores.com): find any UNC
    men's basketball box score since 2003-2004, and [code](https://github.com/gallochris/dadgum-shiny) for the archived Shiny app.


